#############################################################################
# Makefile for building: SR_-_Meta_link_RP_Edition
# Generated by qmake (2.01a) (Qt 4.6.0) on: ons jan 13 02:34:51 2010
# Project:  SR_-_Meta_link_RP_Edition.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile SR_-_Meta_link_RP_Edition.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=nocona -O2 -pipe -msse -msse2 -msse3 -mmmx -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=nocona -O2 -pipe -msse -msse2 -msse3 -mmmx -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib64/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtGui -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/X11R6/lib -lQtNetwork -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dialog.cpp \
		metalinkchat.cpp \
		metalinkconnection.cpp moc_dialog.cpp \
		moc_metalinkchat.cpp \
		moc_metalinkconnection.cpp
OBJECTS       = main.o \
		dialog.o \
		metalinkchat.o \
		metalinkconnection.o \
		moc_dialog.o \
		moc_metalinkchat.o \
		moc_metalinkconnection.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		SR_-_Meta_link_RP_Edition.pro
QMAKE_TARGET  = SR_-_Meta_link_RP_Edition
DESTDIR       = 
TARGET        = SR_-_Meta_link_RP_Edition

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_dialog.h ui_chatdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SR_-_Meta_link_RP_Edition.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtNetwork.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile SR_-_Meta_link_RP_Edition.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile SR_-_Meta_link_RP_Edition.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SR_-_Meta_link_RP_Edition1.0.0 || $(MKDIR) .tmp/SR_-_Meta_link_RP_Edition1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SR_-_Meta_link_RP_Edition1.0.0/ && $(COPY_FILE) --parents dialog.h metalinkchat.h metalinkconnection.h .tmp/SR_-_Meta_link_RP_Edition1.0.0/ && $(COPY_FILE) --parents main.cpp dialog.cpp metalinkchat.cpp metalinkconnection.cpp .tmp/SR_-_Meta_link_RP_Edition1.0.0/ && $(COPY_FILE) --parents dialog.ui chatdialog.ui .tmp/SR_-_Meta_link_RP_Edition1.0.0/ && (cd `dirname .tmp/SR_-_Meta_link_RP_Edition1.0.0` && $(TAR) SR_-_Meta_link_RP_Edition1.0.0.tar SR_-_Meta_link_RP_Edition1.0.0 && $(COMPRESS) SR_-_Meta_link_RP_Edition1.0.0.tar) && $(MOVE) `dirname .tmp/SR_-_Meta_link_RP_Edition1.0.0`/SR_-_Meta_link_RP_Edition1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SR_-_Meta_link_RP_Edition1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_dialog.cpp moc_metalinkchat.cpp moc_metalinkconnection.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp moc_metalinkchat.cpp moc_metalinkconnection.cpp
moc_dialog.cpp: dialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_metalinkchat.cpp: dialog.h \
		metalinkchat.h
	/usr/bin/moc $(DEFINES) $(INCPATH) metalinkchat.h -o moc_metalinkchat.cpp

moc_metalinkconnection.cpp: metalinkconnection.h
	/usr/bin/moc $(DEFINES) $(INCPATH) metalinkconnection.h -o moc_metalinkconnection.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h ui_chatdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h ui_chatdialog.h
ui_dialog.h: dialog.ui
	/usr/bin/uic dialog.ui -o ui_dialog.h

ui_chatdialog.h: chatdialog.ui
	/usr/bin/uic chatdialog.ui -o ui_chatdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dialog.o: dialog.cpp dialog.h \
		metalinkchat.h \
		metalinkconnection.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

metalinkchat.o: metalinkchat.cpp metalinkchat.h \
		dialog.h \
		metalinkconnection.h \
		ui_chatdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metalinkchat.o metalinkchat.cpp

metalinkconnection.o: metalinkconnection.cpp metalinkconnection.h \
		metalinkchat.h \
		dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o metalinkconnection.o metalinkconnection.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_metalinkchat.o: moc_metalinkchat.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_metalinkchat.o moc_metalinkchat.cpp

moc_metalinkconnection.o: moc_metalinkconnection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_metalinkconnection.o moc_metalinkconnection.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

